# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('total_runs', models.IntegerField(blank=True, null=True)),
                ('total_tests', models.IntegerField(blank=True, null=True)),
                ('average_yield', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
